import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "Inter",
          "PingFang SC",
          "Noto Sans SC",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "sans-serif",
        ],
        // App family (doc 02 §3). Applied via the (marketing)/(ielts) layouts.
        // The approved export sets Plus Jakarta Sans + IBM Plex Mono; those are
        // NOT adopted (no new fonts, T0 constraint). Only the export's CJK
        // fallback chain is taken, since those are system faces, not downloads.
        "stage-sans": [
          "var(--font-noto-sans-sc)",
          "Noto Sans SC",
          "PingFang SC",
          "Source Han Sans SC",
          "Microsoft YaHei",
          "sans-serif",
        ],
        "stage-mono": ["var(--font-geist-mono)", "ui-monospace", "monospace"],
      },
      maxWidth: {
        stage: "1200px",
        "stage-narrow": "760px",
        "stage-measure": "68ch",
        "stage-measure-lead": "38ch",
      },
      spacing: {
        "stage-gutter": "var(--stage-gutter)",
        "stage-section": "var(--stage-section-y)",
        "stage-section-tight": "var(--stage-section-y-tight)",
      },
      letterSpacing: {
        "stage-eyebrow": "0.16em",
        "stage-wordmark": "0.34em",
      },
      transitionTimingFunction: {
        "stage-standard": "var(--stage-ease-standard)",
        "stage-out": "var(--stage-ease-out)",
      },
      transitionDuration: {
        "stage-fast": "var(--stage-dur-fast)",
        "stage-base": "var(--stage-dur-base)",
        "stage-slow": "var(--stage-dur-slow)",
        "stage-reveal": "var(--stage-dur-reveal)",
      },
      fontSize: {
        display: ["3.5rem", { lineHeight: "1.14", letterSpacing: "-0.03em" }],
        "display-sm": [
          "2.25rem",
          { lineHeight: "1.22", letterSpacing: "-0.02em" },
        ],
        h2: ["2.5rem", { lineHeight: "1.2", letterSpacing: "-0.02em" }],
        "h2-sm": ["1.875rem", { lineHeight: "1.27", letterSpacing: "-0.02em" }],
        h3: ["1.5rem", { lineHeight: "1.33", letterSpacing: "-0.01em" }],
        "h3-sm": ["1.25rem", { lineHeight: "1.4", letterSpacing: "-0.01em" }],
        "body-lg": ["1.125rem", { lineHeight: "1.56" }],
        body: ["1rem", { lineHeight: "1.625" }],
        caption: ["0.8125rem", { lineHeight: "1.54", letterSpacing: "0.06em" }],
        stat: ["2.75rem", { lineHeight: "1.09", letterSpacing: "-0.02em" }],
        "stat-sm": ["2rem", { lineHeight: "1.125", letterSpacing: "-0.02em" }],
        // App-family type scale, harvested from the approved export. The keys
        // above are the pre-existing marketing steps and are left alone; these
        // are the steps the export actually sets (11/13/15/17/19/20/24/32/40px
        // plus the three display clamps).
        "stage-2xs": ["0.6875rem", { lineHeight: "1.72" }],
        "stage-xs": ["0.8125rem", { lineHeight: "1.72" }],
        "stage-sm": ["0.9375rem", { lineHeight: "1.72" }],
        "stage-body": ["1.0625rem", { lineHeight: "1.72" }],
        "stage-lead": ["1.1875rem", { lineHeight: "1.5" }],
        "stage-h4": ["1.25rem", { lineHeight: "1.22", letterSpacing: "-0.018em" }],
        "stage-h3": ["1.5rem", { lineHeight: "1.22", letterSpacing: "-0.018em" }],
        "stage-h2": ["2rem", { lineHeight: "1.22", letterSpacing: "-0.018em" }],
        "stage-h1": ["2.5rem", { lineHeight: "1.22", letterSpacing: "-0.018em" }],
        "stage-d2": [
          "clamp(2rem, 4vw, 3.5rem)",
          { lineHeight: "1.08", letterSpacing: "-0.03em" },
        ],
        "stage-d1": [
          "clamp(2.25rem, 5vw, 4.5rem)",
          { lineHeight: "1.08", letterSpacing: "-0.03em" },
        ],
        "stage-hero": [
          "clamp(2.75rem, 7.2vw, 6rem)",
          { lineHeight: "1.02", letterSpacing: "-0.045em" },
        ],
      },
      borderRadius: {
        "stage-xs": "var(--stage-radius-xs)",
        "stage-sm": "var(--stage-radius-sm)",
        "stage-md": "var(--stage-radius-md)",
        "stage-lg": "var(--stage-radius-lg)",
        "stage-xl": "var(--stage-radius-xl)",
        "stage-pill": "var(--stage-radius-pill)",
      },
      backgroundImage: {
        "stage-gradient-cta": "var(--stage-gradient-cta)",
        "stage-gradient-text": "var(--stage-gradient-text)",
        "stage-ambient-sky": "var(--stage-ambient-sky)",
      },
      // Colors: existing Explore tokens (brand/ink/line/page) + additive,
      // namespaced stage-* marketing tokens (doc 02). Explore tokens untouched.
      colors: {
        brand: {
          DEFAULT: "#2B46EB",
          800: "#1B2CA0",
          700: "#2237C7",
          600: "#2B46EB",
          500: "#5068F2",
          300: "#B9C4FA",
          100: "#E1E7FE",
          50: "#EEF1FE",
        },
        ink: {
          900: "#0F172A",
          700: "#334155",
          500: "#64748B",
          400: "#94A3B8",
          300: "#CBD5E1",
          100: "#F1F5F9",
          50: "#F8FAFC",
        },
        line: {
          DEFAULT: "#E2E8F0",
          subtle: "#F1F5F9",
        },
        page: "#F6F7FB",
        stage: {
          "blue-25": "var(--stage-blue-25)",
          "blue-50": "var(--stage-blue-50)",
          "blue-100": "var(--stage-blue-100)",
          "blue-200": "var(--stage-blue-200)",
          "blue-300": "var(--stage-blue-300)",
          "blue-400": "var(--stage-blue-400)",
          "blue-500": "var(--stage-blue-500)",
          "blue-600": "var(--stage-blue-600)",
          "blue-700": "var(--stage-blue-700)",
          "blue-800": "var(--stage-blue-800)",
          "blue-900": "var(--stage-blue-900)",
          "blue-950": "var(--stage-blue-950)",
          "neutral-0": "var(--stage-neutral-0)",
          "neutral-25": "var(--stage-neutral-25)",
          "neutral-50": "var(--stage-neutral-50)",
          "neutral-100": "var(--stage-neutral-100)",
          "neutral-200": "var(--stage-neutral-200)",
          "neutral-300": "var(--stage-neutral-300)",
          "neutral-400": "var(--stage-neutral-400)",
          "neutral-500": "var(--stage-neutral-500)",
          "neutral-600": "var(--stage-neutral-600)",
          "neutral-700": "var(--stage-neutral-700)",
          "neutral-800": "var(--stage-neutral-800)",
          "neutral-900": "var(--stage-neutral-900)",
          "green-50": "var(--stage-green-50)",
          "green-100": "var(--stage-green-100)",
          "green-500": "var(--stage-green-500)",
          "green-600": "var(--stage-green-600)",
          "green-700": "var(--stage-green-700)",
          "gold-50": "var(--stage-gold-50)",
          "gold-200": "var(--stage-gold-200)",
          "gold-500": "var(--stage-gold-500)",
          "gold-600": "var(--stage-gold-600)",
          "gold-700": "var(--stage-gold-700)",
          "amber-50": "var(--stage-amber-50)",
          "amber-600": "var(--stage-amber-600)",
          "red-50": "var(--stage-red-50)",
          "red-600": "var(--stage-red-600)",
          "navy-700": "var(--stage-navy-700)",
          "navy-800": "var(--stage-navy-800)",
          "navy-900": "var(--stage-navy-900)",
          "sky-100": "var(--stage-sky-100)",
          "sky-300": "var(--stage-sky-300)",
          white: "var(--stage-white)",
          mist: "var(--stage-mist)",
          bg: "var(--stage-bg)",
          "bg-soft": "var(--stage-bg-soft)",
          "bg-tint": "var(--stage-bg-tint)",
          fg: "var(--stage-fg)",
          "fg-body": "var(--stage-fg-body)",
          "fg-muted": "var(--stage-fg-muted)",
          "fg-subtle": "var(--stage-fg-subtle)",
          "fg-on-dark": "var(--stage-fg-on-dark)",
          "fg-on-dark-muted": "var(--stage-fg-on-dark-muted)",
          primary: "var(--stage-primary)",
          "primary-hover": "var(--stage-primary-hover)",
          "primary-press": "var(--stage-primary-press)",
          "primary-soft": "var(--stage-primary-soft)",
          border: "var(--stage-border)",
          "border-strong": "var(--stage-border-strong)",
          "border-accent": "var(--stage-border-accent)",
          "surface-dark": "var(--stage-surface-dark)",
          focus: "var(--stage-focus)",
          success: "var(--stage-success)",
          "success-soft": "var(--stage-success-soft)",
          warning: "var(--stage-warning)",
          "warning-soft": "var(--stage-warning-soft)",
          danger: "var(--stage-danger)",
          "danger-soft": "var(--stage-danger-soft)",
          accent: "var(--stage-accent)",
          "accent-soft": "var(--stage-accent-soft)",
        },
      },
      boxShadow: {
        card: "0 1px 2px rgba(15,23,42,0.06), 0 4px 12px rgba(15,23,42,0.04)",
        raised: "0 12px 24px rgba(15,23,42,0.12)",
        "stage-xs": "var(--stage-shadow-xs)",
        "stage-sm": "var(--stage-shadow-sm)",
        "stage-md": "var(--stage-shadow-md)",
        "stage-lg": "var(--stage-shadow-lg)",
        "stage-glow": "var(--stage-glow-card)",
        "stage-focus": "var(--stage-focus-ring)",
      },
    },
  },
  plugins: [],
};

export default config;
