/**
 * Types for the IELTS Lab reading module.
 *
 * The practice-record shape intentionally mirrors the original project's
 * `PracticeRecord` so that history stays forward-compatible with its
 * import/export format. Fields the MVP does not populate are omitted rather
 * than filled with placeholder values.
 */

export type ExamCategory = "P1" | "P2" | "P3";
export type ExamFrequency = "high" | "medium" | "low";

/** One row of the catalog, generated by scripts/ielts/build-exam-index.mjs. */
export interface ExamSummary {
  id: string;
  title: string;
  category: ExamCategory;
  frequency: ExamFrequency;
  /** Absent for 84 of 223 records in the source corpus. */
  difficultyScore?: number;
  /** False only for p2-high-26, which has no interactive dataset. */
  interactive: boolean;
  /** Key the exam runner resolves against its manifest. */
  dataKey?: string;
  hasExplanation: boolean;
}

/**
 * An IELTS reading question type, as named by the corpus (`matching`,
 * `true_false_not_given`, …). Kept as a widened string rather than a union:
 * the corpus is the authority, and a new kind appearing there must not turn
 * into a type error in stored history.
 */
export type QuestionType = string;

/** Per-question outcome, as scored by the exam runner. */
export interface AnswerComparison {
  questionId: string;
  userAnswer: string | string[];
  correctAnswer: string | string[];
  isCorrect: boolean;
  /**
   * Resolved from the corpus at save time (record version 2.0.0+). Absent on
   * records written before analytics existed; readers fall back to the live
   * index. Stored rather than always derived so that a later corpus revision
   * cannot retroactively change what a past attempt is reported as.
   */
  questionType?: QuestionType;
}

/** Scoring summary produced by the runner. `total` is weight-adjusted: an
 *  array-valued answer key counts once per element. */
export interface ScoreInfo {
  correct: number;
  total: number;
  totalQuestions: number;
  accuracy: number;
  percentage: number;
  source?: string;
}

/**
 * How an attempt was started. Recorded because it changes how a result should
 * be read: a suite entry was taken under time pressure from the previous two
 * passages, an endless attempt was one of a rapid sequence.
 */
export type PracticeMode = "single" | "endless" | "suite";

/**
 * Suite membership for an attempt.
 *
 * The source project collapsed a three-part suite into ONE record and avoided
 * question-id collisions by rewriting every key as `examId::questionId`. STAGE
 * stores one record per passage instead and groups them here: the suite total
 * is the sum of its entries either way, but per-question ids stay untouched, so
 * question-type analytics keeps working on suite attempts without a special case.
 */
export interface SuiteRef {
  id: string;
  /** 0-based position in the P1 → P2 → P3 sequence. */
  index: number;
  total: number;
}

export interface PracticeRecord {
  id: string;
  examId: string;
  title: string;
  category: ExamCategory | "";
  /** Corpus frequency at the time of the attempt. Absent on pre-2.1.0 records. */
  frequency?: ExamFrequency | "";
  /** The IELTS skill module. Only reading is implemented. */
  type: "reading";
  /**
   * Owner of the record. Always "local" today: STAGE has no learner accounts,
   * so history is browser-local (see storage.ts). Present so that records
   * written now can be attributed without a rewrite if accounts arrive.
   */
  userKey?: string;
  /** ISO timestamps. */
  startTime: string;
  endTime: string;
  /** Seconds, excluding paused time. */
  duration: number;
  score: number;
  totalQuestions: number;
  correctAnswers: number;
  /** Normalised ratio in [0,1], not a percentage. */
  accuracy: number;
  answers: Record<string, string | string[]>;
  answerComparison: Record<string, AnswerComparison>;
  correctAnswerMap: Record<string, string | string[]>;
  /**
   * Questions the learner flagged in the runner. The runner reports these in
   * `metadata.markedQuestions`; keeping them lets a review re-open with the
   * same flags rather than a clean slate.
   */
  markedQuestions?: string[];
  /** Absent on pre-2.1.0 records, which were all single attempts. */
  mode?: PracticeMode;
  suite?: SuiteRef;
  createdAt: string;
  version: string;
}

/** Aggregates shown on the history page. */
export interface PracticeStats {
  totalPractices: number;
  averageAccuracy: number;
  totalTimeSeconds: number;
  /** Consecutive days up to and including the most recent practice day. */
  streakDays: number;
  byCategory: Record<ExamCategory, { practices: number; averageAccuracy: number }>;
}

/** Per-exam rollup of a learner's history, keyed by exam id. */
export interface ExamProgress {
  attempts: number;
  /** Highest accuracy achieved, as a ratio in [0,1]. */
  bestAccuracy: number;
  /** Accuracy of the most recent attempt, as a ratio in [0,1]. */
  lastAccuracy: number;
  /** ISO timestamp of the most recent attempt. */
  lastAttemptAt: string;
  /** Id of the most recent attempt — the target of "review last attempt". */
  lastRecordId: string;
}

/** One point on the score / accuracy trend charts, oldest first. */
export interface TrendPoint {
  /** Attempt id — stable key for the chart. */
  id: string;
  /** 1-based position in the series; the x axis is attempt order, not date. */
  index: number;
  /** Localised short date, shown in the tooltip. */
  date: string;
  title: string;
  category: ExamCategory | "";
  /** Correct answers on this attempt. */
  score: number;
  totalQuestions: number;
  /** Whole percent, 0–100 — charts read better in percent than in [0,1]. */
  accuracy: number;
}

/** Per-question-type rollup driving the weakness breakdown. */
export interface QuestionTypeStat {
  type: QuestionType;
  label: string;
  attempted: number;
  correct: number;
  /** Whole percent, 0–100. */
  accuracy: number;
}
