/**
 * Types for the IELTS Lab reading module.
 *
 * The practice-record shape intentionally mirrors the original project's
 * `PracticeRecord` so that history stays forward-compatible with its
 * import/export format. Fields the MVP does not populate are omitted rather
 * than filled with placeholder values.
 */

export type ExamCategory = "P1" | "P2" | "P3";
export type ExamFrequency = "high" | "medium" | "low";

/** One row of the catalog, generated by scripts/ielts/build-exam-index.mjs. */
export interface ExamSummary {
  id: string;
  title: string;
  category: ExamCategory;
  frequency: ExamFrequency;
  /** Absent for 84 of 223 records in the source corpus. */
  difficultyScore?: number;
  /** False only for p2-high-26, which has no interactive dataset. */
  interactive: boolean;
  /** Key the exam runner resolves against its manifest. */
  dataKey?: string;
  hasExplanation: boolean;
}

/** Per-question outcome, as scored by the exam runner. */
export interface AnswerComparison {
  questionId: string;
  userAnswer: string | string[];
  correctAnswer: string | string[];
  isCorrect: boolean;
}

/** Scoring summary produced by the runner. `total` is weight-adjusted: an
 *  array-valued answer key counts once per element. */
export interface ScoreInfo {
  correct: number;
  total: number;
  totalQuestions: number;
  accuracy: number;
  percentage: number;
  source?: string;
}

export interface PracticeRecord {
  id: string;
  examId: string;
  title: string;
  category: ExamCategory | "";
  type: "reading";
  /** ISO timestamps. */
  startTime: string;
  endTime: string;
  /** Seconds, excluding paused time. */
  duration: number;
  score: number;
  totalQuestions: number;
  correctAnswers: number;
  /** Normalised ratio in [0,1], not a percentage. */
  accuracy: number;
  answers: Record<string, string | string[]>;
  answerComparison: Record<string, AnswerComparison>;
  correctAnswerMap: Record<string, string | string[]>;
  createdAt: string;
  version: string;
}

/** Aggregates shown on the history page. */
export interface PracticeStats {
  totalPractices: number;
  averageAccuracy: number;
  totalTimeSeconds: number;
  byCategory: Record<ExamCategory, { practices: number; averageAccuracy: number }>;
}
